# Generated by Django 4.1.7 on 2023-03-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingmail",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mails.customer",
            ),
        ),
        migrations.AddField(
            model_name="outgoingmail",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mails.customer",
            ),
        ),
    ]
